package provide measure::widget::images 0.1.0

package require Tk

namespace eval ::img {
}

image create photo ::img::delete -format GIF -data {
    R0lGODlhEAAQAIABAIQAAP///yH5BAEAAAEALAAAAAAQABAAAAIjjI+pmwAc3HGy
    PUSvqYpuvWQg40FfSVacBa5nN6JYDI3mzRQAOw==
}

image create photo ::img::start -format GIF -data {
	R0lGODlhEAAQAPQAADNmmTVomzlsnzxvokF0p0V4q0p9sE+CtVSHuliLvl2Qw2CTxmSXymaZzICz
	5oG054W26Iq56Y+86pbA65nM/53O/6LQ/6jT/6/X/7ba/73e/8Ph/8jj/8zl/wAAAAAAACH5BAEA
	AB4ALAAAAAAQABAAAAVNoCeOZFk2jal6TMes5dJ1CzwqHNcptpdswE7ChtAYNR0E7JBpNjuHlQFD
	pU4Mq8Jle5EUYASLOEKwDSoVyKAnoDwEPU/AEYh7AAC7PQQAOw==
}

image create photo ::img::stop -format GIF -data {
	R0lGODlhEAAQAPQAADNmmTZpnDptoDtuoT9ypUR3qkZ5rEp9sE+CtVOGuVWIu1qNwF6RxF+SxWOW
	yWaZzG6f0Hmn1oax3JG54pm/5pnM/53O/6LQ/6jT/6/X/7ba/73e/8Ph/8jj/8zl/wAAACH5BAEA
	AB8ALAAAAAAQABAAAAVb4CeOZGme5gNF0kRRkxRBD+l4eK47ZNP9wGCDtOAYj8gFSbFpOp8KEkJD
	rVoRpENmy+0eSAWMeEwugC/otJpAClje8LigXanb7wESQGBINB4PDQkGAgAoh4gnIQA7
}

image create photo ::img::open -format GIF -data {
	R0lGODlhEAAQALMMAMqjN///ovrvgPPYM/bhRfvyafbiZvjpdPjpVfz1j/TbOPfkav///wAAAAAA
	AAAAACH5BAEAAAwALAAAAAAQABAAAARCkMlJq7046w36ZkAgdqRHAQKCCGwrAKcxDGU9AYsSijwP
	gweAbEYcGH6g14HAbBKCN0CiQK0WEkjQruer1GyfsCYCADs=
}

image create photo ::img::pdf -format GIF -data {
	R0lGODlhEAAQAPesAGYAAGcAAGkAAGwAAG8AAHEAAHMAAHQAAHYAAHkAAI0GBokICIsICIsLC4wI
	CI0ICI0LC5wBAZIICJUICJYICJgICJsICMoKCs0LC9UHB84QEM4WFs4dHfgAAP8AAP4BAfwREfkc
	HM4jI84pKdAuLs89PdA0NNA6Ov4pKeg5OfA2Nv0zM/80NPM6Ovs4OPg6Ov85Of89PdJOTupGRvlB
	QflCQv9KSv9MTP9PT+hWVu9VVehfX/ZTU/xTU/lYWOZqav1mZv9mZvpqav1oaPltbfxtbf9sbOV9
	feh8fPpxcfN6evB+ftyOjuGPj+6OjvKMjOiUlO2Xl+2YmP+SkvGcnP+YmMm+vuCgoPWgoP2iovml
	pfmnp/unp/qoqPyrq/6qqv+tre6xsfSxsfuzs/+0tNPBwdrKysXY2M/Z2eDLy+fPz+/OzvbHx+vU
	1OPY2O/d3f/W1v/X1/DY2PTc3P/a2v/b2//c3Pze3v/e3v/f39Tn597n59zp6d7p6eLo6OLt7enq
	6ujr6+zs7Pfg4PXl5frk5P3l5f/l5efx8efy8uzw8Or19ez29vDw8PDx8fPz8/Tz8/D09PP39/b2
	9vvw8P/z8/j39/r29vD5+fD6+vX7+/L///b8/PT+/vX+/vb///f///j4+Pn5+fv4+Pj6+vr8/Pr9
	/fn///r///v///38/Pz//////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAK0ALAAAAAAQABAA
	AAjsAFsJHCiwA8GDCD0IQNhKhhEjQoQEweEhRY8eNmJEEFjijqZKoVRVWiFGlck6FgSeMMRJU6mX
	K3yYVHUnZSsTgyJNClXKUI0QbEzeoSCQxJxIkCaV8rJkS42Qhoi2GiFHUSNInJKEKQXDR5YpEgSK
	aANIECZCL54UWQIDBIoGAjmo8ZPoTZEWTtZworRlDASBG8z0iaJDhZtNmnjS/NtKgxkkOXZcWdRo
	0s5ScBhjKPNjBpM9ZRvpxMxA4AUrZ9Do6fMnEaNMnDgdgtsqw5EmUKRQwbJlyxcwZKooGJgAAYIC
	yAcMECAAwMJWAQEAOw==
}

